AWSTemplateFormatVersion: '2010-09-09'
Description: base resources for new app

Parameters:
  AppName:
    Type: String
    Description: bucket name for app code


Resources:
  AppBucket:
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AppName}-${AWS::AccountId}-${AWS::Region}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  

Outputs:
  AppBucket:
    Description: s3 bucket for app code
    Value: !Ref AppBucket

